name: testing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    if: (github.event_name == 'push') || (github.event_name == 'pull_request')

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15

        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: pguser
          POSTGRES_DB: mydb

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'

      - name: Run tests
        run: go list -f '{{.Dir}}' -m | xargs go test -v
        env:
          DBURL: "postgres://pguser:secret@localhost:5433/mydb"
