name: testing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    if: (github.event_name == 'push') || (github.event_name == 'pull_request')

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        golang:
          - '1.20'

    steps:
      - uses: actions/checkout@v3

      - name: Setup golang ${{ matrix.golang }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.golang }}

      - run: go list -f '{{.Dir}}' -m | xargs go test -v
